### valid
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "jqn",
    "password": "samplepw"
}


### invalid
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "sample",
    "password": "sp"
}